import type { IconSchema } from "../schemas/icon.schema";

export function iconSeeder(): Omit<IconSchema, "id">[] {
	return [
		{
			name: "user",
			code: "ICON-0000001",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "users",
			code: "ICON-0000002",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "user_plus",
			code: "ICON-0000003",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "user_pen",
			code: "ICON-0000004",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "user_minus",
			code: "ICON-0000005",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "envelope",
			code: "ICON-0000006",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "phone",
			code: "ICON-0000007",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "lock",
			code: "ICON-0000008",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "unlock",
			code: "ICON-0000009",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
		{
			name: "house",
			code: "ICON-0000010",
			slug: "unlock",
			photo: [],
			created_at: new Date(),
			updated_at: new Date(),
		},
	];
}
