name: CI Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

# Cancelar runs anteriores del mismo PR/branch
concurrency:
    group: ci-${{ gitea.ref }}
    cancel-in-progress: true

env:
    NODE_VERSION: "24"
    PNPM_VERSION: "10"

jobs:
    # =========================================================================
    # 🔒 SECURITY SCANNING
    # =========================================================================
    security:
        name: 🔒 Security Scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  format: "table"
                  severity: "CRITICAL,HIGH"
                  exit-code: "0"

    # =========================================================================
    # 📋 CODE QUALITY
    # =========================================================================
    quality:
        name: 📋 Code Quality
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint & Format Check
              run: pnpm run biome:check

    # =========================================================================
    # 🧪 TESTS WITH COVERAGE
    # =========================================================================
    test:
        name: 🧪 Tests
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: test
                    POSTGRES_PASSWORD: test
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            redis:
                image: redis:7
                ports:
                    - 6379:6379
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Setup test environment
              run: cp .env.example .env

            - name: Run Unit Tests with Coverage
              run: pnpm test -- --run --coverage
              env:
                  DATABASE_URL: postgresql://test:test@localhost:5432/test_db
                  REDIS_HOST: localhost
                  REDIS_PORT: 6379

            - name: Run E2E Tests
              run: pnpm run test:e2e -- --run
              env:
                  DATABASE_URL: postgresql://test:test@localhost:5432/test_db
                  REDIS_HOST: localhost
                  REDIS_PORT: 6379

    # =========================================================================
    # 🏗️ BUILD VERIFICATION
    # =========================================================================
    build:
        name: 🏗️ Build
        runs-on: ubuntu-latest
        needs: [quality, test]
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Setup build environment
              run: cp .env.example .env

            - name: Build Client
              run: pnpm run build:client

            - name: Build Server
              run: pnpm run build:serve

    # =========================================================================
    # 🐳 DOCKER BUILD TEST
    # =========================================================================
    docker:
        name: 🐳 Docker Build Test
        runs-on: ubuntu-latest
        needs: [quality, test]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image (no push)
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: production
                  push: false
                  tags: test-build:${{ gitea.sha }}
