name: Deploy Staging

on:
    push:
        branches: [develop]

concurrency:
    group: deploy-staging-${{ gitea.ref }}
    cancel-in-progress: true

env:
    # ⚠️ CAMBIAR: Tu dominio de Gitea
    REGISTRY: gitea.tudominio.com
    IMAGE_NAME: ${{ gitea.repository }}

jobs:
    test:
        name: 🧪 Test & Lint
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: test
                    POSTGRES_PASSWORD: test
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            redis:
                image: redis:7
                ports:
                    - 6379:6379
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Setup test environment
              run: cp .env.example .env

            - name: Lint & Format
              run: pnpm run biome:check

            - name: Unit Tests
              run: pnpm test -- --run

            - name: E2E Tests
              run: pnpm run test:e2e -- --run
              env:
                  DATABASE_URL: postgresql://test:test@localhost:5432/test_db
                  REDIS_HOST: localhost
                  REDIS_PORT: 6379

    build_and_push:
        name: 🐳 Build & Push Image
        needs: test
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - uses: actions/checkout@v4

            - name: Extract version
              id: version
              run: |
                  VERSION="stg-$(git rev-parse --short HEAD)"
                  echo "version=$VERSION" >> $GITEA_OUTPUT
                  echo "📦 Version: $VERSION"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Gitea Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_TOKEN }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  target: production
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
                      ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging

    deploy:
        name: 🚀 Deploy to Staging
        needs: build_and_push
        runs-on: ubuntu-latest
        steps:
            - name: 🚀 Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /home/dokploy/app/my-app-staging

                      # Login al registry de Gitea
                      echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

                      # Inyectar variables de entorno
                      echo "${{ secrets.STAGING_ENV_FILE }}" > .env

                      # Pull de la nueva imagen y deploy
                      docker compose -f docker-compose.production.yml pull
                      docker compose -f docker-compose.production.yml up -d

                      # Limpiar imágenes viejas
                      docker image prune -f

                      echo "✅ Deployed to staging"

    notify:
        name: 📢 Notify
        needs: [build_and_push, deploy]
        if: always()
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Discord Notification
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                  STATUS: ${{ needs.deploy.result }}
                  VERSION: ${{ needs.build_and_push.outputs.version }}
              run: |
                  if [ "$STATUS" == "success" ]; then
                    COLOR=3066993
                    TITLE="✅ Staging Deploy Exitoso"
                  else
                    COLOR=15158332
                    TITLE="❌ Staging Deploy Fallido"
                  fi

                  curl -H "Content-Type: application/json" \
                  -d "{\"embeds\": [{\"title\": \"$TITLE\", \"description\": \"**Version:** $VERSION\n**Commit:** $(git log -1 --pretty=%B)\", \"color\": $COLOR}]}" \
                  $DISCORD_WEBHOOK
